# Inställningar för Azure File Share
# - Namn på share?
# - Url
# - SasToken

# Skapa en lista som  visar filer och directories
# - Kunna klicka på en fil för att ladda ner
# - Kunna klicka på ett directory för att visa filer


####################################
### List files in Azure File Storage
####################################
@account = swarmvfuebbuvstorage
@rootShare = share
@sasToken = ?sv=2020-02-10&ss=bf&srt=sco&sp=rwdlacx&se=2021-09-14T07:01:50Z&st=2021-02-02T00:01:50Z&spr=https&sig=b9YeFeJ0wVQyDveePb2b80l%2Fhxwyr1%2FoeF9n%2B1zAN%2B4%3D


###

GET https://{{account}}.file.core.windows.net/{{rootShare}}{{sasToken}}&restype=directory&comp=list


####################################
### Download a spcific file
####################################
GET https://{{account}}.file.core.windows.net/share/GermanDeveloperBCV17.flf{{sasToken}}
